import 'package:charanju_flutter/core/constants/strings.dart';
import 'package:charanju_flutter/generated/l10n.dart';
import 'package:charanju_flutter/helper/modules/notification_module.dart';

class NotificationData {
  static var notifications = <NotificationModule>[
    NotificationModule(
      urlAvatar: Strings.NOTIFICATION_AVATAR_1,
      notificationMessage: S.current.sentYouMessage,
      receivedTime: "30 min",
      notificationFromUserName: "Karenne ",
      challengeName: "",
      isSeen: true,
      lastMessage: "Display: Last Message",
      username: "Karenne",
      groupMembers: "",
      groupTitle: "",
    ),
    NotificationModule(
      urlAvatar: Strings.NOTIFICATION_AVATAR_2,
      notificationMessage: S.current.wantsToChallengeYou,
      receivedTime: "30 min",
      notificationFromUserName: "Molivis ",
      challengeName: "#newstyle",
      isSeen: false,
      lastMessage: "Display: Last Message",
      username: "Molivis",
      groupMembers: "",
      groupTitle: "",
    ),
    NotificationModule(
      urlAvatar: Strings.NOTIFICATION_AVATAR_1,
      notificationMessage: S.current.youWonTheLastChallenge,
      receivedTime: "30 min",
      notificationFromUserName: "",
      challengeName: " Karenne #newstyle",
      isSeen: false,
      lastMessage: "Display: Last Message",
      username: "Karenne",
      groupMembers: Strings.NOTIFICATION_AVATAR_2,
      groupTitle: "Group chat",
    ),
    NotificationModule(
      urlAvatar: Strings.NOTIFICATION_AVATAR_3,
      notificationMessage: S.current.youWonTheBetOn,
      receivedTime: "30 min",
      notificationFromUserName: "",
      challengeName: "Lennord #dogportrait",
      isSeen: false,
      lastMessage: "Display: Last Message",
      username: "Molivis",
      groupMembers: "",
      groupTitle: "",
    ),
    NotificationModule(
      urlAvatar: Strings.NOTIFICATION_AVATAR_1,
      notificationMessage: S.current.wantsToChallengeYou,
      receivedTime: "1w",
      notificationFromUserName: "Karenne ",
      challengeName: "#newstyle",
      isSeen: false,
      lastMessage: "How dare you challenge me?",
      username: "Karenne",
      groupMembers: "",
      groupTitle: "",
    ),
    NotificationModule(
      urlAvatar: Strings.NOTIFICATION_AVATAR_3,
      notificationMessage: S.current.isYourOpponent,
      receivedTime: "2w",
      notificationFromUserName: "Lennord  ",
      challengeName: "#newstyle",
      isSeen: false,
      lastMessage: "Display: Last Message",
      username: "Lennord",
      groupMembers: "",
      groupTitle: "",
    ),
  ];
}
